# Generated by Django 5.2.5 on 2025-10-04 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='paperpaper.edition'),
        ),
    ]
